project_id = "myncxddatwvtyiioqekh"

[functions.create-tenant-and-user]
verify_jwt = false

[functions.invite-employee]
verify_jwt = true

[functions.sync-employee-roles]
verify_jwt = true

[functions.send-hearing-reminders]
verify_jwt = false

[functions.case-ai-assistant]
verify_jwt = true
